/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiCodeBlock: typeof import('./components/ai/AiCodeBlock.vue')['default']
    AiContextIndicator: typeof import('./components/ai/AiContextIndicator.vue')['default']
    AiConversationList: typeof import('./components/ai/AiConversationList.vue')['default']
    AiDiffView: typeof import('./components/ai/AiDiffView.vue')['default']
    AiEmptyState: typeof import('./components/ai/AiEmptyState.vue')['default']
    AiErrorDisplay: typeof import('./components/ai/AiErrorDisplay.vue')['default']
    AiFileCard: typeof import('./components/ai/AiFileCard.vue')['default']
    AiFilePath: typeof import('./components/ai/AiFilePath.vue')['default']
    AiInputArea: typeof import('./components/ai/AiInputArea.vue')['default']
    AiMessage: typeof import('./components/ai/AiMessage.vue')['default']
    AiMessageActions: typeof import('./components/ai/AiMessageActions.vue')['default']
    AiMessageList: typeof import('./components/ai/AiMessageList.vue')['default']
    AiOperationConfirm: typeof import('./components/ai/AiOperationConfirm.vue')['default']
    AiOptionPrompt: typeof import('./components/ai/AiOptionPrompt.vue')['default']
    AiPanel: typeof import('./components/ai/AiPanel.vue')['default']
    AiPanelHeader: typeof import('./components/ai/AiPanelHeader.vue')['default']
    AiPermissionControl: typeof import('./components/ai/AiPermissionControl.vue')['default']
    AiResultAnimation: typeof import('./components/ai/AiResultAnimation.vue')['default']
    AiSidebarPanel: typeof import('./components/ai/AiSidebarPanel.vue')['default']
    AiStatusIndicator: typeof import('./components/ai/AiStatusIndicator.vue')['default']
    AiToolCard: typeof import('./components/ai/AiToolCard.vue')['default']
    AiToolResultCard: typeof import('./components/ai/AiToolResultCard.vue')['default']
    AiTypingIndicator: typeof import('./components/ai/AiTypingIndicator.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    AppStatusbar: typeof import('./components/common/AppStatusbar.vue')['default']
    AppTitlebar: typeof import('./components/common/AppTitlebar.vue')['default']
    FolderTreeItem: typeof import('./components/FolderTreeItem.vue')['default']
    PromptEditor: typeof import('./components/settings/PromptEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextSelectionMenu: typeof import('./components/ai/TextSelectionMenu.vue')['default']
    ToastContainer: typeof import('./components/common/ToastContainer.vue')['default']
  }
}
